
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Balance = new javax.swing.JButton();
        jButton_withdraw = new javax.swing.JButton();
        jButton_deposit = new javax.swing.JButton();
        jButton_transfer = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelclose = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));
        setUndecorated(true);

        jButton_Balance.setBackground(new java.awt.Color(0, 0, 204));
        jButton_Balance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Balance.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Balance.setText("Check Balance");
        jButton_Balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BalanceActionPerformed(evt);
            }
        });

        jButton_withdraw.setBackground(new java.awt.Color(0, 0, 204));
        jButton_withdraw.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_withdraw.setForeground(new java.awt.Color(255, 255, 255));
        jButton_withdraw.setText("Withdraw");
        jButton_withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_withdrawActionPerformed(evt);
            }
        });

        jButton_deposit.setBackground(new java.awt.Color(0, 0, 204));
        jButton_deposit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_deposit.setForeground(new java.awt.Color(255, 255, 255));
        jButton_deposit.setText("Deposit");
        jButton_deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_depositActionPerformed(evt);
            }
        });

        jButton_transfer.setBackground(new java.awt.Color(0, 0, 204));
        jButton_transfer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_transfer.setForeground(new java.awt.Color(255, 255, 255));
        jButton_transfer.setText("Transfer Cash");
        jButton_transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_transferActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(240, 0, 0));

        jLabelclose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelclose.setText("x");
        jLabelclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcloseMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Transaction");

        jLabelmin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelmin.setText("-");
        jLabelmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelminMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                .addComponent(jLabelmin)
                .addGap(30, 30, 30)
                .addComponent(jLabelclose)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelclose)
                        .addComponent(jLabelmin))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Balance, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButton_withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButton_transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Balance, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_withdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_withdrawActionPerformed
//        String name = jTextField_name.getText();
        String str1 = JOptionPane.showInputDialog("Enter Amount to withdraw");
        if(str1.equals("")){
            JOptionPane.showMessageDialog(null, "enter amount");
        }
        else 
                {
            JOptionPane.showMessageDialog(null, "success");
        }
//        String name = jTextField_name.getText();
    }//GEN-LAST:event_jButton_withdrawActionPerformed

    private void jButton_depositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_depositActionPerformed
//        String str1 = JOptionPane.showInputDialog("Enter Amount to deposit");
        
        String str1 = JOptionPane.showInputDialog("Enter Amount to deposit");

        if(str1.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter Amount ");
        }
        else 
                {
            PreparedStatement ps;
            String query = "INSERT INTO `transactions`(`balance`) VALUES (?)";
            
            
            try {
            ps = DatabaseConnection.getConnection().prepareStatement(query);
            
           
            ps.setString(1, str1);
            
            //display a success message
            if(ps.executeUpdate() > 0) 
            {
                JOptionPane.showMessageDialog(null, "succesfuly deposited");
            
            }
            
        }   catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
            
            
            
            
        }
    }//GEN-LAST:event_jButton_depositActionPerformed

    private void jButton_transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_transferActionPerformed
        String str1 = JOptionPane.showInputDialog("Enter Amount PhoneNumber");
        String str2 = JOptionPane.showInputDialog("Enter Amount");
        
        if(str1.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter Phone Number ");
        }
        
        if(str2.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter Amount ");
        }
        else 
                {
            JOptionPane.showMessageDialog(null, "success");
        }
    }//GEN-LAST:event_jButton_transferActionPerformed

    private void jLabelcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcloseMouseClicked
        System.exit(0);  // Exit program on mouse click
    }//GEN-LAST:event_jLabelcloseMouseClicked

    private void jLabelminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelminMouseClicked
        this.setState(JFrame.ICONIFIED); // minimize window on click
    }//GEN-LAST:event_jLabelminMouseClicked

    private void jButton_BalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BalanceActionPerformed
       
        
//        String roll= "";
        

        PreparedStatement ps;
//        String no = "SELECT  `phone`, `balance` FROM `transactions` WHERE 1";
        
        
        try {
            String no = "select * from users";
//            ps.con.preparedStatement(no);           
            ps = DatabaseConnection.getConnection().prepareStatement(no);
            ResultSet rs = ps.executeQuery();
            JOptionPane.showMessageDialog( null, rs);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
//       JFrame frame = new JFrame();
//            String bigList[] = new String[30];
//
//            JOptionPane.showInputDialog(
//                    frame, 
//                    "Select a item", 
//                    "The List", 
//                    JOptionPane.PLAIN_MESSAGE,
//                    null,
//                    bigList,
//                    "none");
        
//        String str1 = JOptionPane.showInputDialog("Enter Amount to deposit");
            // input dialog returns always a string
//        double fn = Double.parseDouble(str1);


//    JOptionPane.showMessageDialog( null, "The Product is " + ps, "Product", JOptionPane.INFORMATION_MESSAGE);
            
        
        
    }//GEN-LAST:event_jButton_BalanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Balance;
    private javax.swing.JButton jButton_deposit;
    private javax.swing.JButton jButton_transfer;
    private javax.swing.JButton jButton_withdraw;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelclose;
    private javax.swing.JLabel jLabelmin;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    void selectLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
